spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
#    url: jdbc:h2:file:~/test/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
#    driver-class-name: org.h2.Driver
    username: sa
    password:
#  kafka:
#    bootstrap-servers: localhost:9092
#    topic:
#      userCreated: USER_CREATED_TOPIC
security:
  basic:
    enabled: false