spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///home/kirill/projects/webapp-2.0/app/config-properties/{application}/{profile},
            file:///home/kirill/projects/webapp-2.0/app/config-properties/global/{profile}